CREATE TABLE IF NOT EXISTS CCIs (
    CCI_ID INTEGER PRIMARY KEY,
    CCI_Number NVARCHAR (25) NOT NULL,
    CCI_Definition NVARCHAR (500) NOT NULL,
    CCI_Type NVARCHAR (25) NOT NULL,
    CCI_Status NVARCHAR (25) NOT NULL,
    Version DATETIME NOT NULL
);