CREATE TABLE IF NOT EXISTS Vulnerabilities (
    Vulnerability_ID INTEGER PRIMARY KEY,
    UniqueVulnerabilityIdentifier NVARCHAR (100) UNIQUE ON CONFLICT IGNORE NOT NULL,
    VulnerabilityGroupIdentifier NVARCHAR (100),
    VulnerabilityGroupTitle NVARCHAR (100),
    SecondaryVulnerabilityIdentifier NVARCHAR (25),
    VulnerabilityFamilyOrClass NVARCHAR (100),
    VulnerabilityVersion NVARCHAR (25),
    VulnerabilityRelease NVARCHAR (25),
    VulnerabilityTitle NVARCHAR (100) NOT NULL,
    VulnerabilityDescription NVARCHAR,
    RiskStatement NVARCHAR,
    FixText NVARCHAR,
    PublishedDate DATETIME,
    ModifiedDate DATETIME,
    FixPublishedDate DATETIME,
    RawRisk NVARCHAR (25) NOT NULL,
    CVSS_BaseScore NVARCHAR (5),
    CVSS_BaseVector NVARCHAR (25),
    CVSS_TemporalScore NVARCHAR (5),
    CVSS_TemporalVector NVARCHAR (25),
    CheckContent NVARCHAR (2000),
    FalsePositives NVARCHAR (2000),
    FalseNegatives NVARCHAR (2000),
    Documentable NVARCHAR (5),
    Mitigations NVARCHAR (2000),
    MitigationControl NVARCHAR (2000),
    PotentialImpacts NVARCHAR (2000),
    ThirdPartyTools NVARCHAR (500),
    SecurityOverrideGuidance NVARCHAR (2000),
    Overflow NVARCHAR (2000),
    IsActive NVARCHAR (5)
);